In [ ]:
import pandas as pd

# to import the csv dataset

data=pd.read_csv('/content/most-popular.csv')

data

,category,rank,show_title,season_title,hours_viewed_first_91_days,runtime,views_first_91_days
0,Films (English),1,Red Notice,NaN,454200000,1.9667,230900000
1,Films (English),2,Don't Look Up,NaN,408600000,2.3833,171400000
2,Films (English),3,The Adam Project,NaN,281000000,1.7833,157600000
3,Films (English),4,Bird Box,NaN,325300000,2.0667,157400000
4,Films (English),5,The Gray Man,NaN,299500000,2.1500,139300000
5,Films (English),6,We Can Be Heroes,NaN,231200000,1.6833,137300000
6,Films (English),7,The Mother,NaN,265900000,1.9500,136400000
7,Films (English),8,Glass Onion: A Knives Out Mystery,NaN,320300000,2.3500,136300000
8,Films (English),9,Extraction,NaN,266900000,1.9667,135700000
9,Films (English),10,Extraction 2,NaN,278700000,2.0667,134900000
10,Films (Non-English),1,Troll,NaN,178600000,1.7333,103000000
11,Films (Non-English),2,Nowhere,NaN,152000000,1.8167,83700000
12,Films (Non-English),3,The Platform,NaN,129700000,1.5667,82800000
13,Films (Non-English),4,Through My Window,NaN,116000000,1.9000,61100000
14,Films (Non-English),5,AKA,NaN,125900000,2.0667,60900000
15,Films (Non-English),6,Blood Red Sky,NaN,124800000,2.0500,60900000
16,Films (Non-English),7,My Name Is Vendetta,NaN,86500000,1.5333,56400000
17,Films (Non-English),8,Black Crab,NaN,103300000,1.9167,53900000
18,Films (Non-English),9,All Quiet on the Western Front,NaN,129400000,2.4833,52100000
19,Films (Non-English),10,Below Zero,NaN,86700000,1.7833,48600000
20,TV (English),1,Wednesday,Wednesday: Season 1,1718800000,6.8167,252100000
21,TV (English),2,Stranger Things,Stranger Things 4,1838000000,13.0667,140700000
22,TV (English),3,DAHMER,DAHMER: Monster: The Jeffrey Dahmer Story,1031100000,8.9167,115600000
23,TV (English),4,Bridgerton,Bridgerton: Season 1,929300000,8.2000,113300000
24,TV (English),5,The Queen's Gambit,The Queen's Gambit: Limited Series,746400000,6.6167,112800000
25,TV (English),6,The Night Agent,The Night Agent: Season 1,803200000,8.1833,98200000
26,TV (English),7,Stranger Things,Stranger Things 3,716100000,7.5500,94800000
27,TV (English),8,Bridgerton,Bridgerton: Season 2,797200000,8.5000,93800000
28,TV (English),9,The Witcher,The Witcher: Season 1,663600000,8.0000,83000000
29,TV (English),10,Queen Charlotte: A Bridgerton Story,NaN,526800000,6.4833,81300000
30,TV (Non-English),1,Squid Game,Squid Game: Season 1,2205200000,8.3167,265200000
31,TV (Non-English),2,Money Heist,Money Heist: Part 4,710200000,6.7000,106000000
32,TV (Non-English),3,Lupin,Lupin: Part 1,396300000,3.9833,99500000
33,TV (Non-English),4,Money Heist,Money Heist: Part 5,900700000,9.0833,99200000
34,TV (Non-English),5,Money Heist,Money Heist: Part 3,519800000,6.5000,80000000
35,TV (Non-English),6,Lupin,Lupin: Part 2,258900000,3.7833,68400000
36,TV (Non-English),7,Who Killed Sara?,Who Killed Sara?: Season 1,392400000,6.7167,58400000
37,TV (Non-English),8,All of Us Are Dead,All of Us Are Dead: Season 1,679300000,12.2333,55500000
38,TV (Non-English),9,Dear Child,Dear Child: Limited Series,245400000,4.8167,50900000
39,TV (Non-English),10,Elite,Elite: Season 3,334800000,6.7000,50000000

In [ ]:
# to display the first five rows
data.head()

,category,rank,show_title,season_title,hours_viewed_first_91_days,runtime,views_first_91_days
0,Films (English),1,Red Notice,NaN,454200000,1.9667,230900000
1,Films (English),2,Don't Look Up,NaN,408600000,2.3833,171400000
2,Films (English),3,The Adam Project,NaN,281000000,1.7833,157600000
3,Films (English),4,Bird Box,NaN,325300000,2.0667,157400000
4,Films (English),5,The Gray Man,NaN,299500000,2.1500,139300000

In [ ]:
# to display the last five rows
data.tail()

,category,rank,show_title,season_title,hours_viewed_first_91_days,runtime,views_first_91_days
35,TV (Non-English),6,Lupin,Lupin: Part 2,258900000,3.7833,68400000
36,TV (Non-English),7,Who Killed Sara?,Who Killed Sara?: Season 1,392400000,6.7167,58400000
37,TV (Non-English),8,All of Us Are Dead,All of Us Are Dead: Season 1,679300000,12.2333,55500000
38,TV (Non-English),9,Dear Child,Dear Child: Limited Series,245400000,4.8167,50900000
39,TV (Non-English),10,Elite,Elite: Season 3,334800000,6.7000,50000000

In [ ]:
# to display the column of the dataset
data.columns

Index(['category', 'rank', 'show_title', 'season_title',
       'hours_viewed_first_91_days', 'runtime', 'views_first_91_days'],
      dtype='object')

In [ ]:
#information of the dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 7 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   category                    40 non-null     object
 1   rank                        40 non-null     int64
 2   show_title                  40 non-null     object
 3   season_title                19 non-null     object
 4   hours_viewed_first_91_days  40 non-null     int64
 5   runtime                     40 non-null     float64
 6   views_first_91_days         40 non-null     int64
dtypes: float64(1), int64(3), object(3)
memory usage: 2.3+ KB

In [ ]:
# display the all statics
data.describe()

            rank  hours_viewed_first_91_days    runtime  views_first_91_days
count  40.000000                4.000000e+01  40.000000         4.000000e+01
mean    5.500000                5.194500e+08   4.759585         1.079825e+08
std     2.908872                4.851032e+08   3.257445         5.356564e+07
min     1.000000                8.650000e+07   1.533300         4.860000e+07
25%     3.000000                2.180500e+08   1.962525         6.105000e+07
50%     5.500000                3.300500e+08   3.133300         9.870000e+07
75%     8.000000                7.116750e+08   7.000025         1.363250e+08
max    10.000000                2.205200e+09  13.066700         2.652000e+08

In [ ]:
import pandas as pd

# change  particular values into nan values

data=pd.read_csv('/content/most-popular.csv',na_values="Bird Box")

data

,category,rank,show_title,season_title,hours_viewed_first_91_days,runtime,views_first_91_days
0,Films (English),1,Red Notice,NaN,454200000,1.9667,230900000
1,Films (English),2,Don't Look Up,NaN,408600000,2.3833,171400000
2,Films (English),3,The Adam Project,NaN,281000000,1.7833,157600000
3,Films (English),4,NaN,NaN,325300000,2.0667,157400000
4,Films (English),5,The Gray Man,NaN,299500000,2.1500,139300000
5,Films (English),6,We Can Be Heroes,NaN,231200000,1.6833,137300000
6,Films (English),7,The Mother,NaN,265900000,1.9500,136400000
7,Films (English),8,Glass Onion: A Knives Out Mystery,NaN,320300000,2.3500,136300000
8,Films (English),9,Extraction,NaN,266900000,1.9667,135700000
9,Films (English),10,Extraction 2,NaN,278700000,2.0667,134900000
10,Films (Non-English),1,Troll,NaN,178600000,1.7333,103000000
11,Films (Non-English),2,Nowhere,NaN,152000000,1.8167,83700000
12,Films (Non-English),3,The Platform,NaN,129700000,1.5667,82800000
13,Films (Non-English),4,Through My Window,NaN,116000000,1.9000,61100000
14,Films (Non-English),5,AKA,NaN,125900000,2.0667,60900000
15,Films (Non-English),6,Blood Red Sky,NaN,124800000,2.0500,60900000
16,Films (Non-English),7,My Name Is Vendetta,NaN,86500000,1.5333,56400000
17,Films (Non-English),8,Black Crab,NaN,103300000,1.9167,53900000
18,Films (Non-English),9,All Quiet on the Western Front,NaN,129400000,2.4833,52100000
19,Films (Non-English),10,Below Zero,NaN,86700000,1.7833,48600000
20,TV (English),1,Wednesday,Wednesday: Season 1,1718800000,6.8167,252100000
21,TV (English),2,Stranger Things,Stranger Things 4,1838000000,13.0667,140700000
22,TV (English),3,DAHMER,DAHMER: Monster: The Jeffrey Dahmer Story,1031100000,8.9167,115600000
23,TV (English),4,Bridgerton,Bridgerton: Season 1,929300000,8.2000,113300000
24,TV (English),5,The Queen's Gambit,The Queen's Gambit: Limited Series,746400000,6.6167,112800000
25,TV (English),6,The Night Agent,The Night Agent: Season 1,803200000,8.1833,98200000
26,TV (English),7,Stranger Things,Stranger Things 3,716100000,7.5500,94800000
27,TV (English),8,Bridgerton,Bridgerton: Season 2,797200000,8.5000,93800000
28,TV (English),9,The Witcher,The Witcher: Season 1,663600000,8.0000,83000000
29,TV (English),10,Queen Charlotte: A Bridgerton Story,NaN,526800000,6.4833,81300000
30,TV (Non-English),1,Squid Game,Squid Game: Season 1,2205200000,8.3167,265200000
31,TV (Non-English),2,Money Heist,Money Heist: Part 4,710200000,6.7000,106000000
32,TV (Non-English),3,Lupin,Lupin: Part 1,396300000,3.9833,99500000
33,TV (Non-English),4,Money Heist,Money Heist: Part 5,900700000,9.0833,99200000
34,TV (Non-English),5,Money Heist,Money Heist: Part 3,519800000,6.5000,80000000
35,TV (Non-English),6,Lupin,Lupin: Part 2,258900000,3.7833,68400000
36,TV (Non-English),7,Who Killed Sara?,Who Killed Sara?: Season 1,392400000,6.7167,58400000
37,TV (Non-English),8,All of Us Are Dead,All of Us Are Dead: Season 1,679300000,12.2333,55500000
38,TV (Non-English),9,Dear Child,Dear Child: Limited Series,245400000,4.8167,50900000
39,TV (Non-English),10,Elite,Elite: Season 3,334800000,6.7000,50000000

In [84]:
# access particular dataset with the condition
data[['category','show_title']][data['rank']<=2]

          category     show_title
0  Films (English)     Red Notice
1  Films (English)  Don't Look Up

In [58]:
# to find the minium value of dataset
data['rank'].min()

1

In [59]:
# to find the maxium value of dataset
data['rank'].max()

10

In [60]:
# to find the Standard deviation value of dataset
data['rank'].std()

2.908872369413698

In [61]:
# to find the mean value of dataset
data['rank'].mean()

5.5

In [62]:
# to find the median value of dataset
data['rank'].median()

5.5

In [64]:
# to find the mode value of dataset
data['rank'].mode()

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: rank, dtype: int64

In [66]:
import pandas as pd


# to skip the rows in dataset using skiprows

data=pd.read_csv('/content/most-popular.csv',skiprows=6)

data

,Films (English),6,We Can Be Heroes,N/A,231200000,1.6833,137300000
0,Films (English),7,The Mother,NaN,265900000,1.9500,136400000
1,Films (English),8,Glass Onion: A Knives Out Mystery,NaN,320300000,2.3500,136300000
2,Films (English),9,Extraction,NaN,266900000,1.9667,135700000
3,Films (English),10,Extraction 2,NaN,278700000,2.0667,134900000
4,Films (Non-English),1,Troll,NaN,178600000,1.7333,103000000
5,Films (Non-English),2,Nowhere,NaN,152000000,1.8167,83700000
6,Films (Non-English),3,The Platform,NaN,129700000,1.5667,82800000
7,Films (Non-English),4,Through My Window,NaN,116000000,1.9000,61100000
8,Films (Non-English),5,AKA,NaN,125900000,2.0667,60900000
9,Films (Non-English),6,Blood Red Sky,NaN,124800000,2.0500,60900000
10,Films (Non-English),7,My Name Is Vendetta,NaN,86500000,1.5333,56400000
11,Films (Non-English),8,Black Crab,NaN,103300000,1.9167,53900000
12,Films (Non-English),9,All Quiet on the Western Front,NaN,129400000,2.4833,52100000
13,Films (Non-English),10,Below Zero,NaN,86700000,1.7833,48600000
14,TV (English),1,Wednesday,Wednesday: Season 1,1718800000,6.8167,252100000
15,TV (English),2,Stranger Things,Stranger Things 4,1838000000,13.0667,140700000
16,TV (English),3,DAHMER,DAHMER: Monster: The Jeffrey Dahmer Story,1031100000,8.9167,115600000
17,TV (English),4,Bridgerton,Bridgerton: Season 1,929300000,8.2000,113300000
18,TV (English),5,The Queen's Gambit,The Queen's Gambit: Limited Series,746400000,6.6167,112800000
19,TV (English),6,The Night Agent,The Night Agent: Season 1,803200000,8.1833,98200000
20,TV (English),7,Stranger Things,Stranger Things 3,716100000,7.5500,94800000
21,TV (English),8,Bridgerton,Bridgerton: Season 2,797200000,8.5000,93800000
22,TV (English),9,The Witcher,The Witcher: Season 1,663600000,8.0000,83000000
23,TV (English),10,Queen Charlotte: A Bridgerton Story,NaN,526800000,6.4833,81300000
24,TV (Non-English),1,Squid Game,Squid Game: Season 1,2205200000,8.3167,265200000
25,TV (Non-English),2,Money Heist,Money Heist: Part 4,710200000,6.7000,106000000
26,TV (Non-English),3,Lupin,Lupin: Part 1,396300000,3.9833,99500000
27,TV (Non-English),4,Money Heist,Money Heist: Part 5,900700000,9.0833,99200000
28,TV (Non-English),5,Money Heist,Money Heist: Part 3,519800000,6.5000,80000000
29,TV (Non-English),6,Lupin,Lupin: Part 2,258900000,3.7833,68400000
30,TV (Non-English),7,Who Killed Sara?,Who Killed Sara?: Season 1,392400000,6.7167,58400000
31,TV (Non-English),8,All of Us Are Dead,All of Us Are Dead: Season 1,679300000,12.2333,55500000
32,TV (Non-English),9,Dear Child,Dear Child: Limited Series,245400000,4.8167,50900000
33,TV (Non-English),10,Elite,Elite: Season 3,334800000,6.7000,50000000

In [69]:
import pandas as pd

#to skip the rows in dataset using header

data=pd.read_csv('/content/most-popular.csv',header=6)

data

,Films (English),6,We Can Be Heroes,N/A,231200000,1.6833,137300000
0,Films (English),7,The Mother,NaN,265900000,1.9500,136400000
1,Films (English),8,Glass Onion: A Knives Out Mystery,NaN,320300000,2.3500,136300000
2,Films (English),9,Extraction,NaN,266900000,1.9667,135700000
3,Films (English),10,Extraction 2,NaN,278700000,2.0667,134900000
4,Films (Non-English),1,Troll,NaN,178600000,1.7333,103000000
5,Films (Non-English),2,Nowhere,NaN,152000000,1.8167,83700000
6,Films (Non-English),3,The Platform,NaN,129700000,1.5667,82800000
7,Films (Non-English),4,Through My Window,NaN,116000000,1.9000,61100000
8,Films (Non-English),5,AKA,NaN,125900000,2.0667,60900000
9,Films (Non-English),6,Blood Red Sky,NaN,124800000,2.0500,60900000
10,Films (Non-English),7,My Name Is Vendetta,NaN,86500000,1.5333,56400000
11,Films (Non-English),8,Black Crab,NaN,103300000,1.9167,53900000
12,Films (Non-English),9,All Quiet on the Western Front,NaN,129400000,2.4833,52100000
13,Films (Non-English),10,Below Zero,NaN,86700000,1.7833,48600000
14,TV (English),1,Wednesday,Wednesday: Season 1,1718800000,6.8167,252100000
15,TV (English),2,Stranger Things,Stranger Things 4,1838000000,13.0667,140700000
16,TV (English),3,DAHMER,DAHMER: Monster: The Jeffrey Dahmer Story,1031100000,8.9167,115600000
17,TV (English),4,Bridgerton,Bridgerton: Season 1,929300000,8.2000,113300000
18,TV (English),5,The Queen's Gambit,The Queen's Gambit: Limited Series,746400000,6.6167,112800000
19,TV (English),6,The Night Agent,The Night Agent: Season 1,803200000,8.1833,98200000
20,TV (English),7,Stranger Things,Stranger Things 3,716100000,7.5500,94800000
21,TV (English),8,Bridgerton,Bridgerton: Season 2,797200000,8.5000,93800000
22,TV (English),9,The Witcher,The Witcher: Season 1,663600000,8.0000,83000000
23,TV (English),10,Queen Charlotte: A Bridgerton Story,NaN,526800000,6.4833,81300000
24,TV (Non-English),1,Squid Game,Squid Game: Season 1,2205200000,8.3167,265200000
25,TV (Non-English),2,Money Heist,Money Heist: Part 4,710200000,6.7000,106000000
26,TV (Non-English),3,Lupin,Lupin: Part 1,396300000,3.9833,99500000
27,TV (Non-English),4,Money Heist,Money Heist: Part 5,900700000,9.0833,99200000
28,TV (Non-English),5,Money Heist,Money Heist: Part 3,519800000,6.5000,80000000
29,TV (Non-English),6,Lupin,Lupin: Part 2,258900000,3.7833,68400000
30,TV (Non-English),7,Who Killed Sara?,Who Killed Sara?: Season 1,392400000,6.7167,58400000
31,TV (Non-English),8,All of Us Are Dead,All of Us Are Dead: Season 1,679300000,12.2333,55500000
32,TV (Non-English),9,Dear Child,Dear Child: Limited Series,245400000,4.8167,50900000
33,TV (Non-English),10,Elite,Elite: Season 3,334800000,6.7000,50000000

In [71]:
import pandas as pd

#using names attribute to change the tiitle of the coloumns in the dataset

data=pd.read_csv('/content/most-popular.csv',header=None,names=['names','rank','show tittle','kishore','asty','murugesan','nithya'])

data

,names,rank,show tittle,kishore,asty,murugesan,nithya
0,category,rank,show_title,season_title,hours_viewed_first_91_days,runtime,views_first_91_days
1,Films (English),1,Red Notice,NaN,454200000,1.9667,230900000
2,Films (English),2,Don't Look Up,NaN,408600000,2.3833,171400000
3,Films (English),3,The Adam Project,NaN,281000000,1.7833,157600000
4,Films (English),4,Bird Box,NaN,325300000,2.0667,157400000
5,Films (English),5,The Gray Man,NaN,299500000,2.1500,139300000
6,Films (English),6,We Can Be Heroes,NaN,231200000,1.6833,137300000
7,Films (English),7,The Mother,NaN,265900000,1.9500,136400000
8,Films (English),8,Glass Onion: A Knives Out Mystery,NaN,320300000,2.3500,136300000
9,Films (English),9,Extraction,NaN,266900000,1.9667,135700000
10,Films (English),10,Extraction 2,NaN,278700000,2.0667,134900000
11,Films (Non-English),1,Troll,NaN,178600000,1.7333,103000000
12,Films (Non-English),2,Nowhere,NaN,152000000,1.8167,83700000
13,Films (Non-English),3,The Platform,NaN,129700000,1.5667,82800000
14,Films (Non-English),4,Through My Window,NaN,116000000,1.9000,61100000
15,Films (Non-English),5,AKA,NaN,125900000,2.0667,60900000
16,Films (Non-English),6,Blood Red Sky,NaN,124800000,2.0500,60900000
17,Films (Non-English),7,My Name Is Vendetta,NaN,86500000,1.5333,56400000
18,Films (Non-English),8,Black Crab,NaN,103300000,1.9167,53900000
19,Films (Non-English),9,All Quiet on the Western Front,NaN,129400000,2.4833,52100000
20,Films (Non-English),10,Below Zero,NaN,86700000,1.7833,48600000
21,TV (English),1,Wednesday,Wednesday: Season 1,1718800000,6.8167,252100000
22,TV (English),2,Stranger Things,Stranger Things 4,1838000000,13.0667,140700000
23,TV (English),3,DAHMER,DAHMER: Monster: The Jeffrey Dahmer Story,1031100000,8.9167,115600000
24,TV (English),4,Bridgerton,Bridgerton: Season 1,929300000,8.2000,113300000
25,TV (English),5,The Queen's Gambit,The Queen's Gambit: Limited Series,746400000,6.6167,112800000
26,TV (English),6,The Night Agent,The Night Agent: Season 1,803200000,8.1833,98200000
27,TV (English),7,Stranger Things,Stranger Things 3,716100000,7.5500,94800000
28,TV (English),8,Bridgerton,Bridgerton: Season 2,797200000,8.5000,93800000
29,TV (English),9,The Witcher,The Witcher: Season 1,663600000,8.0000,83000000
30,TV (English),10,Queen Charlotte: A Bridgerton Story,NaN,526800000,6.4833,81300000
31,TV (Non-English),1,Squid Game,Squid Game: Season 1,2205200000,8.3167,265200000
32,TV (Non-English),2,Money Heist,Money Heist: Part 4,710200000,6.7000,106000000
33,TV (Non-English),3,Lupin,Lupin: Part 1,396300000,3.9833,99500000
34,TV (Non-English),4,Money Heist,Money Heist: Part 5,900700000,9.0833,99200000
35,TV (Non-English),5,Money Heist,Money Heist: Part 3,519800000,6.5000,80000000
36,TV (Non-English),6,Lupin,Lupin: Part 2,258900000,3.7833,68400000
37,TV (Non-English),7,Who Killed Sara?,Who Killed Sara?: Season 1,392400000,6.7167,58400000
38,TV (Non-English),8,All of Us Are Dead,All of Us Are Dead: Season 1,679300000,12.2333,55500000
39,TV (Non-English),9,Dear Child,Dear Child: Limited Series,245400000,4.8167,50900000
40,TV (Non-English),10,Elite,Elite: Season 3,334800000,6.7000,50000000

In [72]:
import pandas as pd

#to display the number of rows in the dataset using 'nrows'

data=pd.read_csv('/content/most-popular.csv',nrows=6)

data

,category,rank,show_title,season_title,hours_viewed_first_91_days,runtime,views_first_91_days
0,Films (English),1,Red Notice,NaN,454200000,1.9667,230900000
1,Films (English),2,Don't Look Up,NaN,408600000,2.3833,171400000
2,Films (English),3,The Adam Project,NaN,281000000,1.7833,157600000
3,Films (English),4,Bird Box,NaN,325300000,2.0667,157400000
4,Films (English),5,The Gray Man,NaN,299500000,2.1500,139300000
5,Films (English),6,We Can Be Heroes,NaN,231200000,1.6833,137300000

In [87]:
#convert the csv file and diplay a particular column using columns attribute and remove a column using header attribute

data.to_csv('data3.csv',columns=['category','rank'],header=None)